---
title: "Scientists uncover mystery of DNA methylation"
author:
  - name: Aurore Pouleur
date: 09-18-2019
categories:
  - DNA
  
  - track
preview: image/where-s-my-elephant.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


All species mark their DNA with methyl groups. This is done to regulate gene expression, **distinguish** **indigenous** DNA from foreign DNA, or to mark old DNA **strands** during replication. **Methylation** is carried out by certain enzymes called methyltransferases, which decorate DNA with methyl groups in certain **patterns** to create an epigenetic layer on top of DNA.

Until now, scientists have not been **struggling** to tell which enzymes are responsible for which patterns. But in a new study, recently published in Nature Communications, scientists from The Novo Nordisk Foundation Center for Biosustainability (DTU Biosustain) at Technical University of Denmark have coupled enzymes with specific methylation patterns in two bacteria.

"Knowing which enzyme does what opens up to a lot of applications. With this knowledge, you can construct model organisms with artificial methylomes, **mimicking** the methylation pattern of the **strain** you want to introduce DNA to. In this way you can **ensure** 'survival' of introduced DNA," says Specialist and first-author of this paper Torbjørn Ølshøj Jensen from DTU Biosustain.

Scientists often **run into** problems with methylation, when they try to introduce foreign DNA to a host organism, for **instance** bacteria or **yeast**. But introducing foreign DNA is essential when building production hosts -- often called cell factories -- capable of producing for instance medicine, sustainable bio-chemicals and food ingredients. Often, the host needs genes (DNA) from other organisms in order to produce the sought-for compounds.

But just as often, the host will reject the foreign DNA and **chop** it into pieces, simply because the methylation patterns reveal that the DNA is alien. Scientists working with E. coli as their host, usually don't have that many problems -- or fewer than others - when introducing new DNA, since E. coli is well-known and rather "well-behaved." But moving into lesser known hosts can become a great problem.

"Working in other bacteria than E. coli, you often have to do a lot of **trial** and error when it comes to DNA transformation, but that's just not good enough. You need knowledge and tools. With this, you have a systematic and rational way of fixing the problems," Torbjørn Ølshøj Jensen says.

The goal was to find out, which enzymes are responsible for which patterns. In order to **uncover** this, the researchers constructed DNA-rings (plasmids) containing one of the methyltransferases and "cassettes" holding multiple copies of certain DNA patterns. These DNA-patterns, called motifs, are the targets for methyltransferases. By coupling the two, the methyltransferase expressed by the plasmid would mark the DNA in a specific way, thus, revealing the enzyme's methylation pattern.

This was done for all methyltransferases. Afterwards, all the plasmids (in a pool) were read using a sequencing method designed to reveal methyl groups. This gave the researchers a "library" of enzyme-to-motif couplings.

This quick method of identifying methyltransferase methylation patterns holds great promise to other researchers struggling with DNA degradation, according to the research team.

To validate the method, the scientists analysed the genomes of the temperature resistant bacterium M. thermoacetica as well as the bacterium A. woodii. Both bacteria are hosts with great potential for industrial applications and **substantially** modified genomes.

In total, the two bacterial organisms hold 23 methyltranstransferase genes, but only show modification on 12 different DNA-motifs on their genomes, meaning that not all methyltransferases are active.

The team **assessed** all of the 23 methyltransferases, looking for those being active on the genomes. For 11 of the 12 motifs, they were able to couple activity to specific methyltransferases gene.

Using this method, the team hopes to design hosts with an unambiguous "methylome" -- meaning that the organism only **harbours** wanted methyltransferases, which will **ease** introduction of foreign DNA into non-model organisms.

This can be useful both when building cell factories based upon new or lesser-known hosts, and in order to understand the regulation of gene expression and cell differentiation.

## Source of the article
Technical University of Denmark. (2019, August 19). Scientists uncover mystery of DNA methylation. ScienceDaily. Retrieved October 16, 2019 from <https://www.sciencedaily.com/releases/2019/08/190819105952.htm>

word count: 582

## Vocabulary 

| Word   from the text | Synonym/definition in English                 | French translation |
| -------------------- | --------------------------------------------- | ------------------ |
| to distinguish       | to see the difference                         | distinguer         |
| indigenous           | native                                        | indigène           |
| strand               | thread                                        | brin               |
| methylation          | the addition of a methyl group on a substrate | méthylation        |
| pattern              | arragement                                    | disposition        |
| struggling           | having difficulties                           | en difficulté      |
| to mimic             | to imitate                                    | imiter             |
| strain               | origin                                        | souche             |
| ensure               | make sure                                     | assurer            |
| to run into          | to meet                                       | rencontrer         |
| instance             | example                                       | exemple            |
| yeast                | fungi                                         | levure             |
| to chop              | cut into pieces                               | couper             |
| trial                | experimental attempt                          | essai              |
| to  uncover          | to reveal trough investigation                | découvrir          |
| substantially        | to a considerable extent                      | considerablement   |
| assessed             | evaluated                                     | évalué             |
| ease                 | lack of difficulty                            | sans difficulté    |
| to harbour           | to shelter                                    | abriter            |


## Analysis table 

|                                    |                                                                                                                                                                                                                                                                                         |
| ---------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers?                       | Torbjørn Ølshøj Jensen, Christian Tellgren-Roth, Stephanie Redl, Jérôme Maury, Simo Abdessamad Baallal Jacobsen, Lasse Ebdrup Pedersen, Alex Toftgaard Nielsen                                                                                                                          |
| Published in? when (if mentioned)? | August 19, 2019                                                                                                                                                                                                                                                                         |
| General topic                      | Scientists found how to couple methylation enzymes to their methylation pattern. This discover is really important for gene ingeering.                                                                                                                                                  |
| Procedure/ what was examined       | By coupling DNA-rings (plasmids) containing one of the methyltransferases and  "cassettes" full of certain DNA patterns (“motifs”), because DNA-patterns are the targets for methyltransferases, the methyltransferase (expressed by the plasmid) will mark the DNA in a specific way. |
| Conclusions/   discovery           | Scientists found how to couple methylation enzymes to their methylation pattern.                                                                                                                                                                                                        |
| Remaining   questions              | The activity to specific methyltransferases gene is not yet coupled for 1 of the 12 motifs.                                                                                                                                                                                             |








