---
title: "Genetic history of endangered Australian songbird could inspire an encore"
description: |

author:
  - name: Aurore Pouleur
    url: {}
date: 11-11-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



## Source of the article
<https://phys.org/news/2019-10-genetic-history-endangered-australian-songbird.html>

Word count:557

## Vocabulary
|  Word   from the text |   Synonym/definition in English                |  French translation  |
| --------------------- | ---------------------------------------------- | -------------------- |
| endangered            | close to extinction                            | en voie d'extinction |
| sample                | representative piece                           | échantillon          |
| severe                | intense                                        | grave                |
|  widespread           | affecting many people                          | généralisé           |
| breeding              | raising animals                                | élevage              |
| blossom               | flower                                         | fleur                |
| breed                 | procreate                                      | se reproduire        |

## Analysis table
|                              |                                     |
| ---------------------------- | ----------------------------------- |
| Researchers?                 |Ross Crates, George Olah             |
| General topic                |Genetic history of endangered Australian songbird                                    |
| Procedure/ what was examined |blood and DNA samples from museums around the world, extract DNA from tiny fragments of tissue                                     |
| Conclusions/   discovery     |small numbers of birds are travelling long distances to breed with each other, our best chance of saving regent honeyeaters: protecting remaining breeding habitat                                     |
| Remaining   questions        |/                                     |

