---
title: "My English activity log"
description: From now on, you will use this article to include every single activity that you do in English in a chronological order (e.g. reading a book in English, watching TV shows and series in English, going to an English Evening in Mons, travelling to an English-speaking country, playing games in English such as the pretty exciting game LyricsTraining, etc.). You can even write a few lines about what you’ve watched/read/done and recommend certain things to your friends. The sky’s the limit! We value personal initiative and we will be happy to read whatever you have to offer.
  
author:
  - name: Aurore Pouleur
    url: {}
date: 09-10-2019
preview: my-english-activity_files/english_conversation_class.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
# Recommendations

## TV Series

* Game of thrones
* Vikings
* Breaking bad

## Films

* Joker
* The Hobbit
* The Lord of the Rings
* Harry Potter

# My English activity
## Week 4:
* I watched a film 
* I listened to English music 
* I checked the news 

## Week 5:
* I watched some episodes of "Vikings"
* I checked the news
* I read some articles for my portfolio

## Week 6:
* I watched some episodes of "Breaking Bad"
* I checked the news
* I went to the cinema with my brother to watched "Joker"

## Week 6:
* I watched some episodes of "Breacking Bad"
* I watched a film  :"Passenger"
* I read some articles for my portfolio
* I checked the news

## Week 7:
* I watched the Hobbit 1 "An unpexted journey" with my family
* I listened to English music
* I read articles in English
* I checked the news

## Week 8:
* I watched the Hobbit 2 "The Desolation of Smaug"
* I watched for the second time some episodes of Game of thrones
* I watched youtube’s videos
* I read articles for my portfolio


## Week 9:
* I watched the Hobbit 3 "The Battle of the Five Armies"
* I watched some episodes of "Breaking Bad" 
* I checked the news

## Week 10:
* I watched Harry Potter 4: Harry Potter and the Goblet of Fire
* I checked the news
* I read articles for my porfolio


